### ISSUE TITLE
We need a footer for TrackCat

### ISSUE THREAD

**Issue by anuschka** [CodeCatz/TrackCat#36]
We need to create a footer for TrackCat using Bootstrap

**Comment by mojcas** [comment]
Please see my pull request #42 - it adds simple CodeCatz.jpg and a link to CodeCatz@github, for a quick reference in the footer....
 --> But I'm unsure about Bootstrap - can anyone help me with some basic understanding please? Pages look okay, but I'm getting this error in FF console: "Error: Bootstrap's JavaScript requires jQuery". Should a new issue be opened about it? Also, why do we have these bootstrap href/src without https in our base.html? Looking at: http://getbootstrap.com/getting-started/ shouldn't we rather put it in static folder of the project itself actually, similar to css/style.css? It needs some install? How? Where?:) Please help me out.. Thanks! :+1: :thought_balloon:

**Comment by ercchy** [comment]
The error tells you that there is no jQuery in the project, but bootstraps javascripts need it in order to run properly. This is not a bit issue for now, since we are not using any of the bootstrap javascripts yet.

Usually Bootstrap javascripts are use if you want a modal window or some other fancy behavior on the client (read browser) side. We will look into this at a later stage, but for now don't worry about it. 
If you want to you can include jQuery library in the base template, but it has to go before the Bootstrap javascript. And the error will be magically gone :)

The href/scr without the prefix (http or https) is a bit of an overhead at this stage, but we have it so we can talk about it :). 
This is in fact library which is served from CDN (Content delivery network), which is a fancy word for saying that this library is hosted from somewhere else rather than our server. The big deal with this kind of approach is that it is faster for CDN to serve the static files (images, css, javascript) that project needs than if we would serve it from our own server. That is the theory anyway.

We are using this approach because it is faster, but will revisit this issue thoroughly before we will put this project into production.

I hope I answered all of your questions :)... and also I commend you for asking very good questions.

**Comment by mojcas** [comment]
Thanks @ercchy yes, you did. :ok_hand:
Are there any other open issues left for me to do? :smile_cat:

**Comment by ercchy** [comment]
@mojcas I can see plenty open issues, look trough them and find one that you want to tackle...

**Comment by ialja** [comment]
Let's close this now - a basic footer was added by @mojcas in #43. We can open a new issue for a better looking footer, so we don't get functionality mixed up with design :)

**Comment by ialja** [comment]
Created #55 to better describe what we're working on.
