### ISSUE TITLE
Content is overlapping the title on the Projects page

### ISSUE THREAD

**Issue by ialja** [CodeCatz/TrackCat#78]
We have some nice kittens there, but they shouldn't be jumping in the front of the title :grinning: 

![screen shot 2015-01-13 at 18 35 23](https://cloud.githubusercontent.com/assets/1607407/5725471/5b8f8240-9b53-11e4-87d5-656636c76794.png)

P.S.: Also not sure about the title style, with the font, border and all ...

**Comment by livike** [comment]
:) It's because kittens like jumping around...
The reason is the modified h1 in style.css (changes by pull request #63 )
Also the img element was changed to fixed 100px dimensions. This is messing up the image responsiveness... (and also my jumping kittens are small and not so nice ;) )
I'm suggesting that @fbbunny (h1,h2...) and @PettraV (img) fix this in their respective changes.

**Comment by ialja** [comment]
Fixed by one of recent design modifications.
