### ISSUE TITLE
Create model for Tasks

### ISSUE THREAD

**Issue by ialja** [CodeCatz/TrackCat#86]
In `api/models.py`, define a model for Tasks, as discussed during the meetup.

Attributes to define:

- title
- description
- owner
- project
- status
- date created
- date updated

**Comment by senjapollak** [comment]
I can do it!

**Comment by ercchy** [comment]
Grate, then I will assign you :)

**Comment by ercchy** [comment]
There is going to be some collaboration between people who are doing models needed, since the database has relations and all the tables are connected...
Would be good if you wait for all the models to get assigned to people and then collaborate like crazy. 

We have already established we will need some 1:N and N:N relations...

**Comment by ialja** [comment]
@livike will take over this task, we need it done today.

**Comment by ialja** [comment]
Done in #109
